In [11]:
class Node:
    def __init__(self,data=None):
        self.data=data
        self.next=None
class linkedList:
    def __init__(self):
        self.head=None
    def apendNode(self,node):
        if self.head==None:
            self.head=node
            return 
        local=self.head
        tmpNode=None
        while local!=None:
            tmpNode=local
            local=local.next
        tmpNode.next=node
    def printList(self):
        local=self.head
        while local!=None:
            print(local.data)
            local=local.next
    def addNodeInStart(self,node):
        if self.head==None:
            self.head=node
            return
        node.next=self.head
        self.head=node
    def addNodeInPosition(self,node,pos):
        if pos==1:
            self.addNodeInStart(node)
            return
        l=self.lengthOfList()
        if pos> l+1:
            pos=l+1
        local=self.head
        count=1
        tempNode=None
        while count<pos:
            tempNode=local
            local=local.next
            count+=1
        node.next=tempNode.next
        tempNode.next=node
    def lengthOfList(self):
        count1=0
        local=self.head
        while local!=None:
            local=local.next
            count1+=1
        return count1
    def removeNodeInStart(self):
        local=self.head
        self.head=local.next
    def removeNodeInPosition(self,pos):
        if pos==1:
            self.removeNodeInStart()
            return
        l=self.lengthOfList()
        if pos> l:
            pos=l
        local=self.head
        count=1
        tempNode=None
        while count<pos:
            tempNode=local
            local=local.next
            count+=1
        tmep2=tempNode.next
        tempNode.next=tmep2.next
        tmep2.next=None
    def removeNodeInEnd(self):
        l=self.lengthOfList()
        local=self.head
        count=1
        tempNode=None
        if l>1:
            while count<l:
                tempNode=local
                local=local.next
                count+=1
            tempNode.next=None
        else:
            self.head=None
    def printReverse(self):
        self.printRecursive(self.head)
    def printRecursive(self,next1):
        if next1.next==None:
            print(next1.data)
            return
        self.printRecursive(next1.next)
        print(next1.data)


        
        
obj1=linkedList()
obj1.apendNode(Node(1))
obj1.apendNode(Node(2))
obj1.apendNode(Node(3))
obj1.addNodeInStart(Node(4))
obj1.addNodeInPosition(Node(5),9)
obj1.printReverse()
#obj1.removeNodeInPosition(1)
#obj1.removeNodeInStart()
#obj1.removeNodeInEnd()
#obj1.printList()

5
3
2
1
4


In [10]:
class Node:
    def __init__(self,data=None):
        self.data=data
        self.next=None
        self.prev=None
class linkedList:
    def __init__(self):
        self.head=None
        self.tail=None
    def apendNode(self,node):
        if self.head==None:
            self.head=node
            self.tail=node
            return 
        local=self.head
        tmpNode=None
        while local!=None:
            tmpNode=local
            local=local.next
        tmpNode.next=node
        node.prev=tmpNode
        self.tail=node
    def printList(self):
        local=self.head
        while local!=None:
            print(local.data)
            local=local.next
    def addNodeInStart(self,node):
        if self.head==None:
            self.head=node
            self.tail=node
            return
        node.next=self.head
        self.head.prev=node
        self.head=node
    def lengthOfList(self):
        count1=0
        local=self.head
        while local!=None:
            local=local.next
            count1+=1
        return count1
    def addNodeInPosition(self,node,pos):
        l=self.lengthOfList()
        if pos>l+1:
            pos=l+1
        elif pos==1:
            self.addNodeInStart(node)
            return
        local=self.head
        count=1
        tempNode=None
        while count<pos:
            tempNode=local
            local=local.next
            count+=1
        node.next=tempNode.next
        node.prev=tempNode
        tempNode.next=node
        if node.next==None:
            self.tail=node
    def removeNodeInStart(self):
        if self.isEmpty():
            return
        l=self.lengthOfList()
        if l==1:
            self.head=None
            self.tail=None
            return 
        local=self.head
        self.head=local.next
        self.head.prev=None
    def removeNodeInEnd(self):
        if self.isEmpty():
            return
        l=self.lengthOfList()
        if l==1:
            self.head=None
            self.tail=None
            return
        local=self.head
        count=1
        tmpNode=None
        if l>1:
            while count<=l:
                tmpNode=local
                local=local.next
                count+=1
            self.tail=tmpNode.prev
            tmpNode.prev.next=None
        else:
            self.head=None
    def removeNodeInPosition(self,pos):
        l=self.lengthOfList()
        if pos==1:
            self.removeNodeInStart()
        elif pos>l:
            self.removeNodeInEnd()
        else:
            local=self.head
            tmpNode=None
            count=1
            while count<=pos:
                tmpNode=local
                local=local.next
                count+=1
            tmpNode.prev.next=tmpNode.next
    def reverseInNode(self):
        local=self.tail
        while local!=None:
            print(local.data)
            local=local.prev
    def isEmpty(self):
        if self.head==None and self.tail==None:
            return True
        else:
            return False
    def GetByIndex(self,index):
        l=self.lengthOfList()
        if l>index:
            head=self.head
            tempNode=None
            count=-1
            while count!=index:
                tempNode=head
                head=head.next
                count+=1
            return tempNode.data
    
            
            
        
        
        
        
obj1=linkedList()
obj1.apendNode(Node(1))
obj1.apendNode(Node(2))
obj1.apendNode(Node(3))
obj1.addNodeInStart(Node(4))
obj1.addNodeInPosition(Node(5),10)
#obj1.removeNodeInStart()
#obj1.removeNodeInEnd()
obj1.removeNodeInPosition(10)
obj1.removeNodeInPosition(10)
obj1.removeNodeInPosition(10)
#obj1.removeNodeInPosition(10)
#obj1.removeNodeInPosition(10)
#obj1.removeNodeInPosition(10)
print(obj1.GetByIndex(0))
#obj1.printList()
#obj1.reverseInNode()

4


In [3]:
class stack:
    def __init__(self):
        self.__stack=[]
        self.__top=0
    def printStack(self):
        for i in range ((self.__top-1),-1,-1):
            print(self.__stack[i])
    def push(self,data):
        self.__stack.append(data)
        self.__top+=1
    def pop(self):
        if self.isEmpty():
            self.__stack.pop(self.__top-1)
            self.__top-=1
        else:
            return
    def top(self):
        if self.isEmpty():
            return self.__stack[self.__top-1]
    def isEmpty(self):
        if self.__top==0:
            return False
        else:
            return True
        
    
obj1=stack()
obj1.push(1)
obj1.push(2)
obj1.push(3)
obj1.push(4)
obj1.push(5)
obj1.pop()
obj1.pop()
obj1.pop()
obj1.pop()
obj1.pop()
obj1.pop()
obj1.push(6)
obj1.push(7)
obj1.push(8)
obj1.printStack()

8
7
6


In [14]:
class Node:
    def __init__(self,data=None):
        self.data=data
        self.next=None
        self.prev=None
class linkedList:
    def __init__(self):
        self.head=None
        self.tail=None
    def apendNode(self,node):
        if self.head==None:
            self.head=node
            self.tail=node
            return 
        local=self.head
        tmpNode=None
        while local!=None:
            tmpNode=local
            local=local.next
        tmpNode.next=node
        node.prev=tmpNode
        self.tail=node
    def printList(self):
        local=self.head
        while local!=None:
            print(local.data)
            local=local.next
    def addNodeInStart(self,node):
        if self.head==None:
            self.head=node
            self.tail=node
            return
        node.next=self.head
        self.head.prev=node
        self.head=node
    def lengthOfList(self):
        count1=0
        local=self.head
        while local!=None:
            local=local.next
            count1+=1
        return count1
    def addNodeInPosition(self,node,pos):
        l=self.lengthOfList()
        if pos>l+1:
            pos=l+1
        elif pos==1:
            self.addNodeInStart(node)
            return
        local=self.head
        count=1
        tempNode=None
        while count<pos:
            tempNode=local
            local=local.next
            count+=1
        node.next=tempNode.next
        node.prev=tempNode
        tempNode.next=node
        if node.next==None:
            self.tail=node
    def removeNodeInStart(self):
        if self.isEmpty():
            return
        l=self.lengthOfList()
        if l==1:
            self.head=None
            self.tail=None
            return 
        local=self.head
        self.head=local.next
        self.head.prev=None
    def removeNodeInEnd(self):
        if self.isEmpty():
            return
        l=self.lengthOfList()
        if l==1:
            self.head=None
            self.tail=None
            return
        local=self.head
        count=1
        tmpNode=None
        if l>1:
            while count<=l:
                tmpNode=local
                local=local.next
                count+=1
            self.tail=tmpNode.prev
            tmpNode.prev.next=None
        else:
            self.head=None
    def removeNodeInPosition(self,pos):
        l=self.lengthOfList()
        if pos==1:
            self.removeNodeInStart()
        elif pos>l:
            self.removeNodeInEnd()
        else:
            local=self.head
            tmpNode=None
            count=1
            while count<=pos:
                tmpNode=local
                local=local.next
                count+=1
            tmpNode.prev.next=tmpNode.next
    def reverseInNode(self):
        local=self.tail
        while local!=None:
            print(local.data)
            local=local.prev
    def isEmpty(self):
        if self.head==None and self.tail==None:
            return True
        else:
            return False
    def GetByIndex(self,index):
        l=self.lengthOfList()
        if l>index:
            head=self.head
            tempNode=None
            count=-1
            while count!=index:
                tempNode=head
                head=head.next
                count+=1
            return tempNode.data
                
class stack:
    def __init__(self):
        self.__stack=linkedList()
        self.__top=0
    def printStack(self):
        self.__stack.reverseInNode()
    def push(self,data):
        self.__stack.apendNode(Node(data))
        self.__top+=1
    def pop(self):
        if self.isEmpty():
            self.__stack.removeNodeInEnd()
            self.__top-=1
        else:
            return
    def top(self):
        if self.isEmpty():
            return self.__stack.GetByIndex(self.__top-1)
    def isEmpty(self):
        if self.__top==0:
            return False
        else:
            return True
        
obj1=stack()
obj1.push(1)
obj1.push(2)
obj1.push(3)
obj1.push(4)
obj1.push(5)
obj1.pop()
obj1.pop()
obj1.pop()
obj1.pop()
obj1.pop()
obj1.pop()
obj1.push(6)
obj1.push(7)
obj1.push(8)
obj1.printStack()

8
7
6


In [15]:
import numpy as np
def CreatArray():
    m=np.zeros((2,3),dtype=int)
    for i in range (2):
        for j in range (3):
            print(f'ENTER your index here [{i}][{j}]')
            m[i][j]=int(input(""))
    return m
def Display(m):
    for i in range (2):
        for j in range (3):
            print(m[i][j],end="")
        print()
        
arr=CreatArray()
Display(arr)

ENTER your index here [0][0]
1
ENTER your index here [0][1]
2
ENTER your index here [0][2]
8
ENTER your index here [1][0]
9
ENTER your index here [1][1]
3
ENTER your index here [1][2]
7
128
937


In [27]:
class Queue:
    def __init__(self):
        self.__queue=[]
        self.__rare=-1
        self.__front=0
    def isEmpty(self):
        if self.__rare>-1:
            return True
    def Enqueue(self,data):
        self.__queue.append(data)
        self.__rare+=1
    def Dequeue(self):
        if self.isEmpty():
            self.__queue.pop(self.__front)
            self.__rare-=1
        else:
            return
    def printQueue(self):
        if self.isEmpty():
             for i in range ((self.__rare),-1,-1):
                if i==0:
                    print(self.__queue[i],end="")
                else:
                    print(self.__queue[i],end=",")
        else:
            return

obj=Queue()
obj.Enqueue(1)
obj.Enqueue(2)
obj.Enqueue(3)
obj.Enqueue(4)
obj.Dequeue()
obj.Dequeue()
obj.printQueue()

4,3

In [4]:
class Queue:
    def __init__(self):
        self.__queue=[".",".",".",".","."]
        self.__rare=-1
        self.__front=0
    def isEmpty(self):
        for i in self.__queue:
            if i==".":
                return True
    def Enqueue(self,data):
        if self.isEmpty():
            if self.__rare>=4 and self.__front>0:
                self.__rare=0
            else:
                self.__rare+=1
            self.__queue[self.__rare]=data
        else:
            return
    def Dequeue(self):
        if self.__front==0:
            self.__queue[self.__front]="."
            self.__front=1
        elif self.__front==5:
            self.__front=0
            self.__queue[self.__front]="."
            self.__front=1
        else:
            self.__queue[self.__front]="."
            self.__front+=1
    def printQueue(self):
        print(self.__queue)
        
obj=Queue()
obj.Enqueue(1)
obj.Enqueue(2)
obj.Enqueue(3)
obj.Enqueue(4)
obj.Enqueue(5)
obj.Dequeue()
obj.Dequeue()
obj.Enqueue(6)
obj.Enqueue(7)
obj.Dequeue()
obj.Dequeue()
obj.Dequeue()
obj.Dequeue()
obj.Dequeue()
obj.Enqueue(1)
obj.Enqueue(2)
obj.Dequeue()
obj.printQueue()

['.', '.', '.', 2, '.']


In [15]:
class Similarities:
    def __init__(self,user1,user2):
        self.user1=user1
        self.user2=user2
        self.larger=[]
        self.smaller=[]
        self.match=0
    def lengthCheck(self):
        if len(self.user1)>len(self.user2):
            self.larger.append(len(self.user1))
            self.larger.append(self.user1)
            self.smaller.append(len(self.user2))
            self.smaller.append(self.user2)
        else:
            self.larger.append(len(self.user2))
            self.larger.append(self.user2)
            self.smaller.append(len(self.user1))
            self.smaller.append(self.user1)
    def MatchingAndPercentage(self):
        self.lengthCheck()
        count=0
        for i in range (self.smaller[0]):
            for x in range (self.larger[0]):
                if self.smaller[1][i]==self.larger[1][x]:
                    count+=1
        self.match=(count/self.larger[0])*100
        print(f"Percentage match:{self.match}")
u1=input("Enter here:")
u2=input("Enter here:")
obj=Similarities(u1,u2)
obj.MatchingAndPercentage()

Enter here:asdfgh
Enter here:asdcvb
[6, 'asdfgh']
[6, 'asdcvb']
Percentage match:50.0


In [68]:
class stack:
    def __init__(self):
        self.__stack=[]
        self.__top=0
        self.__final=""
        self.__rank=[["(",")"],["^"],["/","*"],["+","-"]]
    def main(self,data):
        index1=0
        index2=0
        for i in data:
            if (ord(i)>=48 and ord(i)<=57) or (ord(i)>=65 and ord(i)<=90) or (ord(i)>=97 and ord(i)<=122):
                self.__final+=str(i)
            elif i in self.__rank:
                index=0
                for x in range (4):
                    if i in self.__rank[x]:
                        index1=x
                    if self.__stack[self.__top-1] in self.__rank[x]:
                        index2=x
                if index2==index1 or index2>
                
                
    def push(self,data):
        self.__stack.append(data)
        self.__top+=1
    def pop(self):
        keep=""
        if self.isEmpty():
            keep=self.__stack[self.__top-1]
            self.__stack.pop(self.__top-1)
            self.__top-=1
            return keep
        else:
            return
    def top(self):
        if self.isEmpty():
            return self.__stack[self.__top-1]
    def isEmpty(self):
        if self.__top==0:
            return False
        else:
            return True
obj=stack()
obj.main("A+B-C")

SyntaxError: invalid syntax (Temp/ipykernel_11916/183730128.py, line 20)

In [11]:
import numpy as np
def y(sal):
    dt={}
    for i in sal:
        if i not in dt:
            dt.update({i:1})
        else:
            dt[i]+=1
    for ky,val in dt.items():
        for key,value in dt.items():
            if ky==key:
                pass
            else:
                if val>1:
                    if val==value:
                        return True
                else:
                    pass
    return False

salami = np.array([4,5,6,6,4,3,6,4])
x=y(salami)
print(x)

{4: 3, 5: 1, 6: 3, 3: 1}
3
3
True


In [17]:
def is_james_bond(data):
    sett=[7,0,0]
    count=2
    for i in data:
        if count==-1:
            break
        if i==sett[count]:
            count-=1
    if count==-1:
        print(True)
    else:
        print(False)
is_james_bond([1,2,4,0,0,7,5])

True


In [22]:
import numpy as np
def strength_difference(room):
    before=[]
    after=[]
    final=[]
    bul=False
    for i in range (4):
        bul=False
        for z in range (4):
            if i==z:
                bul=True
            elif bul==False:
                before.append(room[i][z])
            elif bul==True:
                after.append(room[i][z])
    for t in range (6):
        if t==2:
            final.append(after[t]-before[t+1])
        elif t==3:
            final.append(after[t]-before[t-1])
        else:
            final.append(after[t]-before[t])
    print(final)

clubroom = np.array([
[1,  2,  9,  7],
[4,  5,  1,  8],
[3,  6,  2,  7],
[2,  8,  6,  3]
])
strength_difference(clubroom)

[-2, 6, 5, -5, 0, 1]


In [48]:
import numpy as np
def atm_triangle(n):
    ary=np.zeros((n,n),dtype=int)
    count=0
    for i in range (n):
        for x in range (i+1):
            if x==i or x==0:
                ary[i][x]=i+1
            else:
                sum1=0
                for z in range (x+1):
                    sum1+=ary[i-1][z]
                ary[i][x]=sum1
    for q in range (n):
        for w in range (n):
            if ary[q][w]==0:
                break
            else:
                print(ary[q][w],end=" ")
        print()
    
    
n = 5
atm_triangle(n)

[[ 1  0  0  0  0]
 [ 2  2  0  0  0]
 [ 3  4  3  0  0]
 [ 4  7 10  4  0]
 [ 5 11 21 25  5]]
1 
2 2 
3 4 3 
4 7 10 4 
5 11 21 25 5 


In [66]:
import numpy as np
def create_fence(dis,dep):
    row=0
    col=0
    for i in range (len(dis)):
        row+=1
        for x in dis[i]:
            if i==0:
                col+=1
    row=row+(2*dep)
    col=col+(2*dep)
    print(row,col)
    ary=np.zeros((row,col),dtype=int)
    for z in range (row):
        for y in range (col):
            if z<dep or y<dep or y>=col-dep or z>=row-dep:
                ary[z][y]=8
            else:
                ary[z][y]=dis[z-dep][y-dep]
    print(ary)
    
        

dep=2
dis = np.array([[2,3,4], [3,4,6],[3,4,6],[3,4,6]])
create_fence(dis,dep)

8 7
[[8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]
 [8 8 2 3 4 8 8]
 [8 8 3 4 6 8 8]
 [8 8 3 4 6 8 8]
 [8 8 3 4 6 8 8]
 [8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]]


In [2]:
def is_james_bond(data):
    sett=[7,0,0]
    count=2
    for i in data:
        if count==-1:
            break
        if i==sett[count]:
            count-=1
    if count==-1:
        print(True)
    else:
        print(False)
is_james_bond([1,7,2,0,4,5,0])


False


In [3]:
class stack:
    def __init__(self,data):
        self.__stack=[]
        self.__top=0
        self.data=data
        self.__rank=[["(",")"],["^"],["/","*"],["+","-"]]
        count=0
        count1=0
        for x in range (4):
            if self.data in self.__rank[x]:
                break
            else:
                count+=1
        if isEmpty() and count!=0:
            for q in range (4):
                if self.__stack[self.__top-1] in self.__rank[q]:
                    break
                else:
                    count1+=1
            if count>count1:
                self.push(self.data)
            else:
                self.add(top())
                self.pop()
                self.push(self.data)
        else:
            if self.data==")":
                while self.__stack[self.__top-1]!="(":
                    self.add(top())
                    self.pop()
                self.pop()
            else:
                self.push(data)
    def push(self,data):
        self.__stack.append(data)
        self.__top+=1
    def pop(self):
        if self.isEmpty():
            self.__stack.pop(self.__top-1)
            self.__top-=1
        else:
            return
    def top(self):
        if self.isEmpty():
            return self.__stack[self.__top-1]
    def isEmpty(self):
        if self.__top==0:
            return False
        else:
            return True

class main:
    def __init__(self,data):
        self.data=data
        self.__final=""
    def process(self):
        for i in self.data:
            if (ord(i)>=48 and ord(i)<=57) or (ord(i)>=65 and ord(i)<=90) or (ord(i)>=97 and ord(i)<=122):
                self.__final+=str(i)
            else:
                self.stack(i)
    def add(self,data):
        self.__final+=data
    def print1(self):
        print(self.__final)

obj1=main("A+C-D/(A*B)")
obj1.print1()

In [30]:
class stack:
    def __init__(self):
        self.__stack=[]
        self.__top=0
    def printStack(self):
        for i in range ((self.__top-1),-1,-1):
            print(self.__stack[i],end="")
        print()
    def push(self,data):
        self.__stack.append(data)
        self.__top+=1
    def pop(self):
        if self.isEmpty()==False:
            self.__stack.pop(self.__top-1)
            self.__top-=1
        else:
            return
    def top(self):
        if self.isEmpty()==False:
            return self.__stack[self.__top-1]
    def isEmpty(self):
        if self.__top==0:
            return True
        else:
            return False
        
class expressionConverter:
    def __init__(self,data):
        self.__rank=[['+','-'],['/','*'],['^']]
        self.__final=""
        self.equation=data
        self.__stack=stack()
    def postFix(self):
        for i in self.equation:
            if self.isAlphaNumeric(i):
                self.__final+=str(i)
            else:
                self.placeCharPostFix(i)
        if self.__stack.isEmpty()==False:
            while self.__stack.isEmpty()==False:
                self.__final+=self.__stack.top()
                self.__stack.pop()
    def isAlphaNumeric(self,char):
        if (ord(char)>=48 and ord(char)<=57) or (ord(char)>=65 and ord(char)<=90) or (ord(char)>=97 and ord(char)<=122):
            return True
        return False
    def placeCharPostFix(self,data1):
        if self.__stack.isEmpty() or data1=='(':
            self.__stack.push(data1)
        elif data1==')':
            self.popOnBracketClosed()
        else:
            while self.RankCheck(data1)==False:
                if self.__stack.isEmpty():
                    break
                self.__final+=self.__stack.top()
                self.__stack.pop()
            self.__stack.push(data1)
            #self.__stack.printStack()
    def RankCheck(self,data1):
        topRank=0
        dataRank=0
        if self.__stack.top()=='(':
            return True
        for z in range (len(self.__rank)):
            if self.__stack.top() in self.__rank[z]:
                break
            else:
                topRank+=1
        for q in range (len(self.__rank)):
            if data1 in self.__rank[q]:
                break
            else:
                dataRank+=1
        if dataRank>topRank:
            return True
        else:
            return False
    def popOnBracketClosed(self):
        while self.__stack.top()!='(':
            #self.__stack.printStack()
            self.__final+=self.__stack.top()
            self.__stack.pop()
        self.__stack.pop()
        #self.__stack.printStack()
    def printFinal(self):
        print(self.__final)
obj1=expressionConverter("(A+B/C*(D+C)-F)")
obj1.postFix()
obj1.printFinal()

ABC/DC+*+F-


In [10]:
class DoublyNode:
    def __init__(self, elem, next1=None, prev=None):
        self.elem = elem
        self.next = next1 
        self.prev = prev 
class circularDoublyLinkList:
    def __init__(self):
        self.head=None
        self.tail=None
    def apendNode(self,node):
        if self.head==None:
            self.head=node
            self.tail=node
            return 
        local=self.head
        tmpNode=None
        while True:
            tmpNode=local
            local=local.next
            if local==self.tail.next or local==None:
                break
        tmpNode.next=node
        node.prev=tmpNode
        self.tail=node
        node.next=self.head
    def printList(self):
        if self.head==None:
            return
        local=self.head
        while True:
            print(local.elem)
            local=local.next
            if local==self.tail.next or local==None:
                break
    def getTop(self):
        return self.head
    def lengthOfList(self):
        count1=0
        local=self.head
        while True:
            local=local.next
            count1+=1
            if local==self.tail.next or local==None:
                break
        return count1
    def removeNode(self):
        if self.isEmpty():
            return
        l=self.lengthOfList()
        if l==1:
            self.head=None
            self.tail=None
            return 
        local=self.head
        self.head=local.next
        self.head.prev=self.tail
    def reverseInNode(self):
        linkList1=[]
        local=self.tail
        while True:
            linkList1.append(local)
            local=local.prev
            if local==self.head.prev or local==None:
                break
        self.creatLinkList(linkList1)
    def creatLinkList(self,list1):
        self.clear()
        for i in list1:
            self.apendNode(i)
    def isEmpty(self):
        if self.head==None and self.tail==None:
            return True
        else:
            return False
    def clear(self):
        self.head=None
        self.tail=None
    
obj1=circularDoublyLinkList()
obj1.printList()
obj1.apendNode(DoublyNode(1))
#obj1.printList()
obj1.apendNode(DoublyNode(2))
#obj1.printList()
obj1.apendNode(DoublyNode(3))
#obj1.printList()
#print(obj1.getTop().elem)
obj1.reverseInNode()
obj1.printList()

3
2
1


In [2]:
#1] a.
#   b.

def row_min_max(arr):
    minList=[]
    final=0
    keep=0
    for z in range (len(arr)):
        keep=arr[z][0]
        for i in range (len(arr[z])):
            if keep>arr[z][i]:
                keep=arr[z][i]
        minList.append(keep)
        keep=0
    length=len(minList)
    index0=minList[0]
    if length==2:
        if minList[0]>minList[1]:
            final=minList[0]
        else:
            final=minList[1]
    else:
        for y in range (len(minList)):
            if index0<minList[y]:
                index0=minList[y]
        final=index0
    return final



#warr=[[2,7,5],[9,3,8],[1,4,6]]
arr=[[2,7,5,10],[9,13,8,4]]
print(row_min_max(arr))

4


In [16]:
#2] 1) a. Node does not consist of previoues.
#      b. Signly linked list consume less memeory

#2)
class Node:
    def __init__(self,e,n):
        self.elem=e
        self.next=n
def creatList(lst):
    head=Node(lst[0],None)
    tail=head
    for i in range (1,len(lst)):
        n=Node(lst[i],None)
        tail.next=n
        tail=tail.next
    return head
#########################################
def is_sorted_des(head):
    temp=head
    while temp.next!=None:
        if temp.elem<temp.next.elem:
            return False
        temp=temp.next
    return True

#lst=[10,20,5,15,25]
lst=[40,30,20,15,5]
head=creatList(lst)
print(is_sorted_des(head))

True


In [9]:
class Node:
    def __init__(self,e,n):
        self.elem=e
        self.next=n
def creatList(lst):
    head=Node(lst[0],None)
    tail=head
    for i in range (1,len(lst)):
        n=Node(lst[i],None)
        tail.next=n
        tail=tail.next
    return head
def remove_middle(head):
    count=0
    temp=head
    while temp!=None:
        count+=1
        temp=temp.next
    if count%2==0:
        count=count/2
        count=count-2
    else:
        count=count//2
        count=count-1
    temp2=head
    while count!=0:
        temp2=temp2.next
        count-=1
    temp2.next=temp2.next.next
    temp3=head
    while temp3!=None:
        print(temp3.elem,end=" ")
        temp3=temp3.next

#lst=[10,20,5,15,25]
lst=[10,20,30,15,5,70,80,90,50]
head=creatList(lst)
remove_middle(head)

10 20 30 15 70 80 90 50 

In [1]:
class Node:
    def __init__(self,e,n):
        self.elem=e
        self.next=n
def creatList(lst):
    head=Node(lst[0],None)
    tail=head
    for i in range (1,len(lst)):
        n=Node(lst[i],None)
        tail.next=n
        tail=tail.next
    return head
def revomeSimilarNode(head):
    temp=head
    lst=[]
    while temp.next!=None:
        if temp.elem==temp.next.elem:
            temp.next=temp.next.next
        else:
            temp=temp.next
        lst.append(temp.elem)
    return lst

lst=[10,10,30,30,5,70,80,90]
head=creatList(lst)
print(revomeSimilarNode(head))

[10, 30, 30, 5, 70, 80, 90]


In [2]:
lst=[5,3,9,10,22,1,2,7]
index=0

for i in range (len(lst)):
    index=i
    for j in range (i+1,len(lst)):
        if lst[j]<lst[index]:
            index=j
    temp=lst[i]
    lst[i]=lst[index]
    lst[index]=temp
print(lst)

[1, 2, 3, 5, 7, 9, 10, 22]


In [4]:
lst=[5,3,9,10,22,1,2,7]

for i in range (len(lst)):
    for j in range (0,(len(lst)-i-1)):
        if lst[j]>lst[j+1]:
            temp=lst[j+1]
            lst[j+1]=lst[j]
            lst[j]=temp
print(lst)

[1, 2, 3, 5, 7, 9, 10, 22]


In [8]:
lst=[5,3,9,10,22,1,2,7]
val=0

for i in range (1,len(lst)):
    val=lst[i]
    j=i-1
    while j>=0:
        if lst[j]<val:
            break
        lst[j+1]=lst[j]
        j-=1
    lst[j+1]=val
print(lst)

[1, 2, 3, 5, 7, 9, 10, 22]


In [1]:
def binarySearch(lst,L,H,X):
    if L>H:
        return -1
    mid=(H+L)//2
    if lst[mid]==X:
        return mid
    elif X>lst[mid]:
        final=binarySearch(lst,mid+1,H,X)
    else:
        final=binarySearch(lst,L,mid-1,X)
    return final
    
def factorial(q):
    if q==1:
        return 1
    final=q*factorial(q-1)
    return final
    






lst=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
L=0
H=len(lst)
H=H-1
X=8
final=binarySearch(lst,L,H,X)
if final==-1:
    print("Number not found")
else:
    print("The index of the number that found is:",final)

The index of the number that found is: 7
